<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            // ─── MOROCCAN ───────────────────────────────────────────────
            [
                'title' => 'Moroccan Tagine with Chicken and Olives',
                'title_ar' => 'طاجين الدجاج بالزيتون المغربي',
                'description' => 'A classic slow-cooked Moroccan tagine with preserved lemons and green olives.',
                'description_ar' => 'طاجين مغربي تقليدي مطهو ببطء مع الليمون المحفوظ والزيتون الأخضر.',
                'cuisine' => 'moroccan',
                'prep_time' => 20,
                'cook_time' => 60,
                'servings' => 4,
                'is_halal' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['tagine', 'chicken', 'classic'],
                'ingredients' => [
                    ['name' => 'Chicken pieces', 'amount' => '1', 'unit' => 'kg'],
                    ['name' => 'Onions', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Preserved lemon', 'amount' => '1', 'unit' => 'piece'],
                    ['name' => 'Green olives', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Garlic', 'amount' => '4', 'unit' => 'cloves'],
                    ['name' => 'Cumin', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Turmeric', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Ginger powder', 'amount' => '½', 'unit' => 'tsp'],
                    ['name' => 'Saffron', 'amount' => '1 pinch', 'unit' => ''],
                    ['name' => 'Olive oil', 'amount' => '3', 'unit' => 'tbsp'],
                    ['name' => 'Fresh parsley & coriander', 'amount' => '1', 'unit' => 'bunch'],
                ],
                'steps' => [
                    'Marinate chicken with garlic, cumin, turmeric, ginger, saffron, salt, and olive oil for 30 minutes.',
                    'Heat oil in a tagine or heavy pot. Brown the chicken on all sides over medium-high heat.',
                    'Add sliced onions and cook until softened, about 5 minutes.',
                    'Add 1 cup water, cover and simmer on low heat for 40 minutes.',
                    'Add preserved lemon (cut into quarters) and olives. Cook for 10 more minutes.',
                    'Garnish with fresh parsley and coriander. Serve with crusty bread or couscous.',
                ],
                'steps_ar' => [
                    'تتبل الدجاج بالثوم والكمون والكركم والزنجبيل والزعفران والملح وزيت الزيتون لمدة 30 دقيقة.',
                    'سخن الزيت في طاجين أو وعاء ثقيل. حمر الدجاج من جميع الجهات.',
                    'أضف البصل المشرح واطبخ حتى يتلين.',
                    'أضف كوب ماء، غطي واطبخ على نار هادئة 40 دقيقة.',
                    'أضف الليمون المحفوظ والزيتون واطبخ 10 دقائق إضافية.',
                    'زيني بالبقدونس والكزبرة الطازجين. قدمي مع الخبز أو الكسكس.',
                ],
            ],
            [
                'title' => 'Harira Soup',
                'title_ar' => 'شوربة الحريرة',
                'description' => 'Traditional Moroccan tomato and lentil soup, perfect for breaking the Ramadan fast.',
                'description_ar' => 'شوربة مغربية تقليدية بالطماطم والعدس، مثالية للإفطار في رمضان.',
                'cuisine' => 'moroccan',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 6,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['soup', 'ramadan', 'lentils', 'vegan-friendly'],
                'ingredients' => [
                    ['name' => 'Red lentils', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Chickpeas (cooked)', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Crushed tomatoes', 'amount' => '400', 'unit' => 'g'],
                    ['name' => 'Onion', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Celery stalks', 'amount' => '2', 'unit' => 'stalks'],
                    ['name' => 'Fresh coriander', 'amount' => '½', 'unit' => 'bunch'],
                    ['name' => 'Tomato paste', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Turmeric', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Cinnamon', 'amount' => '½', 'unit' => 'tsp'],
                    ['name' => 'Ginger', 'amount' => '½', 'unit' => 'tsp'],
                    ['name' => 'Flour', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Lemon juice', 'amount' => '1', 'unit' => 'lemon'],
                ],
                'steps' => [
                    'Sauté diced onion and celery in oil until soft.',
                    'Add spices (turmeric, ginger, cinnamon, pepper) and stir for 1 minute.',
                    'Add crushed tomatoes and tomato paste. Cook 5 minutes.',
                    'Add lentils and 1.5 litres of water. Bring to boil, then simmer 20 minutes.',
                    'Add chickpeas and continue simmering 10 minutes.',
                    'Mix flour with cold water to make a paste. Stir into soup to thicken.',
                    'Add fresh coriander and lemon juice. Season with salt. Serve hot.',
                ],
                'steps_ar' => [
                    'قلي البصل والكرفس في الزيت حتى يتلينا.',
                    'أضف البهارات وحرك دقيقة واحدة.',
                    'أضف الطماطم المهروسة ومعجون الطماطم. اطبخ 5 دقائق.',
                    'أضف العدس ولتر ونصف ماء. اتركه يغلي ثم اخفض الحرارة 20 دقيقة.',
                    'أضف الحمص واستمر في الطهي 10 دقائق.',
                    'اخلط الطحين بالماء البارد وأضفه للشوربة لتكثيفها.',
                    'أضف الكزبرة وعصير الليمون. قدمها ساخنة.',
                ],
            ],
            [
                'title' => 'Moroccan Couscous with Seven Vegetables',
                'title_ar' => 'كسكس بالخضروات السبع',
                'description' => 'The iconic Friday couscous dish with seven colorful vegetables and chickpeas.',
                'description_ar' => 'طبق الكسكس الجمعة المشهور بسبع خضروات ملونة والحمص.',
                'cuisine' => 'moroccan',
                'prep_time' => 30,
                'cook_time' => 60,
                'servings' => 6,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['couscous', 'friday', 'vegetarian', 'family'],
                'ingredients' => [
                    ['name' => 'Couscous', 'amount' => '500', 'unit' => 'g'],
                    ['name' => 'Carrots', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Zucchini', 'amount' => '2', 'unit' => 'medium'],
                    ['name' => 'Turnips', 'amount' => '2', 'unit' => 'small'],
                    ['name' => 'Pumpkin', 'amount' => '200', 'unit' => 'g'],
                    ['name' => 'Cabbage', 'amount' => '¼', 'unit' => 'head'],
                    ['name' => 'Chickpeas', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Tomatoes', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Onion', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Ras el hanout', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Butter', 'amount' => '50', 'unit' => 'g'],
                ],
                'steps' => [
                    'Steam couscous according to package instructions, fluffing with a fork.',
                    'In a large pot, sauté onion and tomatoes in olive oil until soft.',
                    'Add ras el hanout, salt, and pepper. Cook 2 minutes.',
                    'Add chickpeas and 1.5 litres water. Bring to boil.',
                    'Add harder vegetables first (carrots, turnips, pumpkin). Cook 15 minutes.',
                    'Add softer vegetables (zucchini, cabbage). Cook 10 more minutes.',
                    'Mix butter into couscous. Mound couscous on a large plate, top with vegetables and broth.',
                ],
                'steps_ar' => [
                    'بخر الكسكس حسب تعليمات العبوة مع تهويته بالشوكة.',
                    'في وعاء كبير، قلي البصل والطماطم بزيت الزيتون حتى يتلينا.',
                    'أضف رأس الحانوت والملح والفلفل. اطبخ دقيقتين.',
                    'أضف الحمص ولتر ونصف ماء. اتركه يغلي.',
                    'أضف الخضروات الصلبة أولاً. اطبخ 15 دقيقة.',
                    'أضف الخضروات اللينة. اطبخ 10 دقائق إضافية.',
                    'اخلط الزبدة مع الكسكس. قدمه في طبق كبير مع الخضروات والمرق.',
                ],
            ],

            // ─── EGYPTIAN ───────────────────────────────────────────────
            [
                'title' => 'Koshari',
                'title_ar' => 'الكشري',
                'description' => 'Egypt\'s beloved street food — a hearty mix of rice, lentils, pasta, and spiced tomato sauce.',
                'description_ar' => 'أكثر الأكلات الشعبية المصرية حباً — خليط من الأرز والعدس والمكرونة وصلصة الطماطم المبهرة.',
                'cuisine' => 'egyptian',
                'prep_time' => 15,
                'cook_time' => 40,
                'servings' => 4,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'tags' => ['street food', 'budget', 'vegan', 'filling'],
                'ingredients' => [
                    ['name' => 'Rice', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Brown lentils', 'amount' => '½', 'unit' => 'cup'],
                    ['name' => 'Small pasta (elbow)', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Chickpeas', 'amount' => '½', 'unit' => 'cup'],
                    ['name' => 'Onions', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Crushed tomatoes', 'amount' => '400', 'unit' => 'g'],
                    ['name' => 'Garlic', 'amount' => '4', 'unit' => 'cloves'],
                    ['name' => 'Vinegar', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Cumin', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Chili flakes', 'amount' => '1', 'unit' => 'tsp'],
                ],
                'steps' => [
                    'Cook lentils in water until tender but not mushy, about 20 minutes.',
                    'Cook rice in salted water. Cook pasta separately until al dente.',
                    'For the tomato sauce: sauté garlic in oil, add crushed tomatoes, vinegar, cumin, salt, and chili. Simmer 15 minutes.',
                    'Slice onions into thin rings and fry in oil until deep golden and crispy. Set aside.',
                    'In a large pot, layer: rice, lentils, pasta, and chickpeas. Mix gently.',
                    'Serve in bowls: the mixed base, topped with tomato sauce, then crispy onions.',
                ],
                'steps_ar' => [
                    'اطبخ العدس في ماء حتى ينضج دون أن يتفتت.',
                    'اطبخ الأرز في ماء مالح. اطبخ المكرونة بشكل منفصل.',
                    'لصلصة الطماطم: قلي الثوم، أضف الطماطم والخل والكمون والملح والشطة. اطبخ 15 دقيقة.',
                    'قطع البصل حلقات رفيعة وقلها في الزيت حتى تصبح ذهبية ومقرمشة.',
                    'في وعاء كبير، ادمج الأرز والعدس والمكرونة والحمص.',
                    'قدم في أطباق: القاعدة المخلوطة، ثم صلصة الطماطم، ثم البصل المقرمش.',
                ],
            ],
            [
                'title' => 'Ful Medames',
                'title_ar' => 'فول مدمس',
                'description' => 'Egypt\'s national breakfast — slow-cooked fava beans with lemon, garlic, and cumin.',
                'description_ar' => 'فطور مصر الوطني — فول مطبوخ ببطء مع الليمون والثوم والكمون.',
                'cuisine' => 'egyptian',
                'prep_time' => 5,
                'cook_time' => 10,
                'servings' => 4,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['breakfast', 'budget', 'quick', 'protein'],
                'ingredients' => [
                    ['name' => 'Canned fava beans', 'amount' => '2', 'unit' => 'cans (400g each)'],
                    ['name' => 'Garlic', 'amount' => '3', 'unit' => 'cloves'],
                    ['name' => 'Lemon juice', 'amount' => '2', 'unit' => 'lemons'],
                    ['name' => 'Cumin', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Olive oil', 'amount' => '3', 'unit' => 'tbsp'],
                    ['name' => 'Fresh parsley', 'amount' => '¼', 'unit' => 'bunch'],
                    ['name' => 'Tomato', 'amount' => '1', 'unit' => 'diced'],
                    ['name' => 'Chili (optional)', 'amount' => '1', 'unit' => 'small'],
                ],
                'steps' => [
                    'Heat fava beans in their liquid in a pan over medium heat.',
                    'Mash half the beans with a fork for a creamy texture, leave the rest whole.',
                    'Add crushed garlic, cumin, salt, and lemon juice. Stir and heat through.',
                    'Transfer to a serving bowl. Drizzle with olive oil.',
                    'Top with diced tomato, chopped parsley, and chili if desired.',
                    'Serve with warm Egyptian bread (aish baladi).',
                ],
                'steps_ar' => [
                    'سخن الفول مع ماءه في مقلاة على نار متوسطة.',
                    'اهرس نصف الفول بالشوكة للحصول على قوام كريمي.',
                    'أضف الثوم المهروس والكمون والملح وعصير الليمون.',
                    'انقل لطبق التقديم وصب عليه زيت الزيتون.',
                    'زين بالطماطم المكعبة والبقدونس والشطة.',
                    'قدم مع خبز عيش بلدي دافئ.',
                ],
            ],

            // ─── LEBANESE ───────────────────────────────────────────────
            [
                'title' => 'Mujaddara',
                'title_ar' => 'مجدرة',
                'description' => 'Lebanese comfort food — lentils and rice topped with caramelized onions.',
                'description_ar' => 'طعام الراحة اللبناني — عدس وأرز مع بصل مكرمل.',
                'cuisine' => 'lebanese',
                'prep_time' => 10,
                'cook_time' => 35,
                'servings' => 4,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['budget', 'vegan', 'protein', 'comfort food'],
                'ingredients' => [
                    ['name' => 'Brown lentils', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Rice', 'amount' => '½', 'unit' => 'cup'],
                    ['name' => 'Onions', 'amount' => '3', 'unit' => 'large'],
                    ['name' => 'Cumin', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Olive oil', 'amount' => '4', 'unit' => 'tbsp'],
                    ['name' => 'Salt and pepper', 'amount' => 'to taste', 'unit' => ''],
                ],
                'steps' => [
                    'Cook lentils in 3 cups salted water for 20 minutes until almost tender.',
                    'Add rinsed rice to the lentils. Cook on low heat until rice is done and water absorbed.',
                    'Meanwhile, slice onions and fry in olive oil over medium heat, stirring occasionally.',
                    'Continue cooking onions for 20-25 minutes until deeply caramelized and golden.',
                    'Stir cumin into the lentil-rice mixture. Season with salt and pepper.',
                    'Serve topped with caramelized onions. Eat with yogurt and salad.',
                ],
                'steps_ar' => [
                    'اطبخ العدس في 3 أكواب ماء مالح لمدة 20 دقيقة.',
                    'أضف الأرز المغسول للعدس. اطبخ على نار هادئة.',
                    'في هذه الأثناء، شرح البصل وقله في زيت الزيتون.',
                    'استمر في الطهي 25-20 دقيقة حتى يتكرمل البصل.',
                    'أضف الكمون لخليط العدس والأرز. تبل بالملح والفلفل.',
                    'قدم مع البصل المكرمل والزبادي والسلطة.',
                ],
            ],
            [
                'title' => 'Fattoush Salad',
                'title_ar' => 'سلطة الفتوش',
                'description' => 'A vibrant Lebanese bread salad with crispy pita, fresh vegetables, and sumac dressing.',
                'description_ar' => 'سلطة خبز لبنانية نابضة بالحياة مع خبز مقرمش وخضروات طازجة وصلصة السماق.',
                'cuisine' => 'lebanese',
                'prep_time' => 15,
                'cook_time' => 10,
                'servings' => 4,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'tags' => ['salad', 'quick', 'fresh', 'summer'],
                'ingredients' => [
                    ['name' => 'Pita bread', 'amount' => '2', 'unit' => 'pieces'],
                    ['name' => 'Romaine lettuce', 'amount' => '1', 'unit' => 'head'],
                    ['name' => 'Tomatoes', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Cucumber', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Radishes', 'amount' => '6', 'unit' => 'pieces'],
                    ['name' => 'Green onions', 'amount' => '4', 'unit' => 'stalks'],
                    ['name' => 'Fresh mint', 'amount' => '¼', 'unit' => 'cup'],
                    ['name' => 'Sumac', 'amount' => '1', 'unit' => 'tbsp'],
                    ['name' => 'Lemon juice', 'amount' => '3', 'unit' => 'tbsp'],
                    ['name' => 'Olive oil', 'amount' => '3', 'unit' => 'tbsp'],
                ],
                'steps' => [
                    'Cut pita into small pieces and toast or fry until crispy.',
                    'Chop all vegetables into bite-sized pieces.',
                    'Make the dressing: whisk together lemon juice, olive oil, sumac, salt, and pepper.',
                    'Combine all vegetables in a large bowl.',
                    'Add pita chips just before serving to keep them crispy.',
                    'Pour dressing over salad and toss well. Serve immediately.',
                ],
                'steps_ar' => [
                    'قطع الخبز قطعاً صغيرة وحمصه حتى يتقرمش.',
                    'قطع جميع الخضروات إلى قطع صغيرة.',
                    'اعمل الصلصة: اخفق عصير الليمون وزيت الزيتون والسماق والملح والفلفل.',
                    'ادمج جميع الخضروات في وعاء كبير.',
                    'أضف قطع الخبز قبل التقديم مباشرة.',
                    'صب الصلصة وقلب جيداً. قدم فوراً.',
                ],
            ],

            // ─── SOUTH ASIAN ───────────────────────────────────────────
            [
                'title' => 'Dhal (Red Lentil Curry)',
                'title_ar' => 'دال - كاري العدس الأحمر',
                'description' => 'A comforting South Asian spiced red lentil dish, perfect with rice or flatbread.',
                'description_ar' => 'طبق عدس أحمر جنوب آسيوي مريح بالتوابل، مثالي مع الأرز أو الخبز.',
                'cuisine' => 'south_asian',
                'prep_time' => 10,
                'cook_time' => 25,
                'servings' => 4,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'tags' => ['curry', 'budget', 'vegan', 'protein', 'quick'],
                'ingredients' => [
                    ['name' => 'Red lentils', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Onion', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Tomatoes', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Garlic', 'amount' => '4', 'unit' => 'cloves'],
                    ['name' => 'Ginger', 'amount' => '1', 'unit' => 'inch piece'],
                    ['name' => 'Turmeric', 'amount' => '½', 'unit' => 'tsp'],
                    ['name' => 'Cumin seeds', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Garam masala', 'amount' => '1', 'unit' => 'tsp'],
                    ['name' => 'Chili powder', 'amount' => '½', 'unit' => 'tsp'],
                    ['name' => 'Fresh coriander', 'amount' => '¼', 'unit' => 'bunch'],
                    ['name' => 'Vegetable oil', 'amount' => '2', 'unit' => 'tbsp'],
                ],
                'steps' => [
                    'Rinse lentils and cook in 3 cups water with turmeric until soft, about 15 minutes.',
                    'Heat oil in a pan. Add cumin seeds and let them sizzle for 30 seconds.',
                    'Add diced onion, garlic, and ginger. Cook until golden, about 8 minutes.',
                    'Add diced tomatoes, chili powder, and salt. Cook until tomatoes break down.',
                    'Pour the cooked lentils into the tomato mixture. Stir and simmer 5 minutes.',
                    'Add garam masala. Taste and adjust seasoning.',
                    'Garnish with fresh coriander. Serve with rice or naan.',
                ],
                'steps_ar' => [
                    'اغسل العدس واطبخه في 3 أكواب ماء مع الكركم حتى يتلين.',
                    'سخن الزيت في مقلاة. أضف بذور الكمون وانتظر 30 ثانية.',
                    'أضف البصل والثوم والزنجبيل. اطبخ حتى يذهب.',
                    'أضف الطماطم المكعبة ومسحوق الشطة والملح. اطبخ حتى تتفتت الطماطم.',
                    'أضف العدس المطبوخ للخليط. حرك واطبخ 5 دقائق.',
                    'أضف الغارام ماسالا. تذوق واضبط التتبيل.',
                    'زين بالكزبرة. قدم مع الأرز أو النان.',
                ],
            ],
            [
                'title' => 'Chicken Biryani',
                'title_ar' => 'برياني الدجاج',
                'description' => 'Fragrant layered rice and chicken dish with warm spices — a South Asian festive classic.',
                'description_ar' => 'طبق الأرز والدجاج العطر بالبهارات الدافئة — كلاسيكي احتفالي جنوب آسيوي.',
                'cuisine' => 'south_asian',
                'prep_time' => 30,
                'cook_time' => 50,
                'servings' => 6,
                'is_halal' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['biryani', 'festive', 'rice', 'chicken'],
                'ingredients' => [
                    ['name' => 'Basmati rice', 'amount' => '2', 'unit' => 'cups'],
                    ['name' => 'Chicken pieces', 'amount' => '1', 'unit' => 'kg'],
                    ['name' => 'Yogurt', 'amount' => '1', 'unit' => 'cup'],
                    ['name' => 'Onions', 'amount' => '3', 'unit' => 'large'],
                    ['name' => 'Tomatoes', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Garlic paste', 'amount' => '1', 'unit' => 'tbsp'],
                    ['name' => 'Ginger paste', 'amount' => '1', 'unit' => 'tbsp'],
                    ['name' => 'Biryani spice mix', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Saffron (optional)', 'amount' => '1 pinch', 'unit' => ''],
                    ['name' => 'Fresh mint', 'amount' => '¼', 'unit' => 'cup'],
                    ['name' => 'Oil or ghee', 'amount' => '4', 'unit' => 'tbsp'],
                ],
                'steps' => [
                    'Marinate chicken with yogurt, garlic, ginger, biryani spice, and salt for 1 hour.',
                    'Parboil basmati rice until 70% cooked. Drain and set aside.',
                    'Fry sliced onions until deep golden brown. Set half aside for garnish.',
                    'Add chicken to remaining onions and cook until chicken is nearly done.',
                    'In a heavy pot, layer: half the rice, the chicken, then remaining rice.',
                    'Dissolve saffron in warm milk and drizzle over rice. Add mint leaves.',
                    'Seal with foil and lid. Cook on very low heat for 25 minutes (dum cooking).',
                    'Gently mix before serving. Garnish with fried onions.',
                ],
                'steps_ar' => [
                    'تتبل الدجاج بالزبادي والثوم والزنجبيل وتوابل البرياني والملح لساعة.',
                    'اطبخ الأرز حتى 70% ثم صفيه.',
                    'قلي شرائح البصل حتى تصبح ذهبية داكنة. احتفظ بنصفها للتزيين.',
                    'أضف الدجاج للبصل المتبقي واطبخ حتى يكاد الدجاج ينضج.',
                    'في وعاء ثقيل، طبق: نصف الأرز، ثم الدجاج، ثم الأرز المتبقي.',
                    'أذب الزعفران في حليب دافئ وصبه على الأرز. أضف ورق النعناع.',
                    'أغلق بالألومنيوم والغطاء. اطبخ على نار جداً هادئة 25 دقيقة.',
                    'اخلط برفق قبل التقديم. زين بالبصل المقلي.',
                ],
            ],

            // ─── WEST AFRICAN ──────────────────────────────────────────
            [
                'title' => 'Jollof Rice',
                'title_ar' => 'أرز جولوف',
                'description' => 'The beloved West African one-pot tomato rice dish, rich with spices and flavor.',
                'description_ar' => 'طبق أرز الطماطم الغرب أفريقي المحبوب، غني بالتوابل والنكهة.',
                'cuisine' => 'west_african',
                'prep_time' => 15,
                'cook_time' => 45,
                'servings' => 6,
                'is_halal' => true,
                'is_vegetarian' => false,
                'tags' => ['one-pot', 'rice', 'festive', 'family'],
                'ingredients' => [
                    ['name' => 'Long grain rice', 'amount' => '2', 'unit' => 'cups'],
                    ['name' => 'Chicken (optional)', 'amount' => '500', 'unit' => 'g'],
                    ['name' => 'Crushed tomatoes', 'amount' => '400', 'unit' => 'g'],
                    ['name' => 'Red bell pepper', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Onions', 'amount' => '2', 'unit' => 'large'],
                    ['name' => 'Scotch bonnet pepper', 'amount' => '1', 'unit' => 'small'],
                    ['name' => 'Tomato paste', 'amount' => '2', 'unit' => 'tbsp'],
                    ['name' => 'Chicken stock', 'amount' => '2', 'unit' => 'cups'],
                    ['name' => 'Bay leaves', 'amount' => '2', 'unit' => 'pieces'],
                    ['name' => 'Mixed spices (thyme, curry powder)', 'amount' => '2', 'unit' => 'tsp'],
                    ['name' => 'Vegetable oil', 'amount' => '4', 'unit' => 'tbsp'],
                ],
                'steps' => [
                    'Blend tomatoes, bell peppers, onion, and scotch bonnet into a smooth paste.',
                    'Heat oil in a large pot. Fry the tomato paste for 5 minutes until darkened.',
                    'Add blended tomato mixture and cook on medium heat, stirring often, for 20 minutes.',
                    'Add tomato paste, spices, salt, and bay leaves. Cook 5 more minutes.',
                    'Add washed rice and chicken stock. Stir to combine.',
                    'Cover tightly and cook on low heat until rice is tender, about 30 minutes. Check and stir halfway.',
                    'Fluff rice and serve with fried plantains and coleslaw.',
                ],
                'steps_ar' => [
                    'اخلط الطماطم والفلفل الأحمر والبصل والفلفل الحار في الخلاط.',
                    'سخن الزيت في وعاء كبير. قلي معجون الطماطم 5 دقائق.',
                    'أضف خليط الطماطم الممزوج واطبخ على نار متوسطة 20 دقيقة مع التحريك.',
                    'أضف معجون الطماطم والبهارات والملح وورق الغار. اطبخ 5 دقائق.',
                    'أضف الأرز المغسول ومرق الدجاج. حرك للدمج.',
                    'غطي بإحكام واطبخ على نار هادئة 30 دقيقة. تفقد وحرك في المنتصف.',
                    'هوي الأرز وقدم مع الموز المقلي وسلطة الكول سلو.',
                ],
            ],
            [
                'title' => 'Lentil Soup (Shorbat Adas)',
                'title_ar' => 'شوربة العدس',
                'description' => 'Simple, warming lentil soup loved across the Arab world — especially during Ramadan.',
                'description_ar' => 'شوربة عدس بسيطة ودافئة محبوبة في العالم العربي — خاصة في رمضان.',
                'cuisine' => 'lebanese',
                'prep_time' => 10,
                'cook_time' => 30,
                'servings' => 4,
                'is_halal' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_ramadan_friendly' => true,
                'tags' => ['soup', 'ramadan', 'quick', 'budget', 'vegan'],
                'ingredients' => [
                    ['name' => 'Red lentils', 'amount' => '1.5', 'unit' => 'cups'],
                    ['name' => 'Onion', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Carrot', 'amount' => '1', 'unit' => 'large'],
                    ['name' => 'Garlic', 'amount' => '3', 'unit' => 'cloves'],
                    ['name' => 'Cumin', 'amount' => '1.5', 'unit' => 'tsp'],
                    ['name' => 'Turmeric', 'amount' => '½', 'unit' => 'tsp'],
                    ['name' => 'Lemon juice', 'amount' => '1', 'unit' => 'lemon'],
                    ['name' => 'Olive oil', 'amount' => '2', 'unit' => 'tbsp'],
                ],
                'steps' => [
                    'Sauté chopped onion, carrot, and garlic in olive oil until soft.',
                    'Add cumin and turmeric. Stir for 1 minute.',
                    'Add rinsed lentils and 1.2 litres of water.',
                    'Bring to boil, then simmer on low heat for 20 minutes until lentils are very soft.',
                    'Blend the soup until smooth using an immersion blender.',
                    'Add lemon juice and season with salt. Add water if too thick.',
                    'Serve hot with a drizzle of olive oil and a lemon wedge.',
                ],
                'steps_ar' => [
                    'قلي البصل والجزر والثوم في زيت الزيتون حتى يتلينوا.',
                    'أضف الكمون والكركم. حرك دقيقة واحدة.',
                    'أضف العدس المغسول ولتراً و200 مل ماء.',
                    'اتركه يغلي ثم اخفض الحرارة 20 دقيقة حتى ينضج العدس جداً.',
                    'اخلط الشوربة حتى تصبح ناعمة بالخلاط العمودي.',
                    'أضف عصير الليمون وتبل بالملح. أضف ماء إن كانت كثيفة جداً.',
                    'قدم ساخنة مع رذاذ زيت الزيتون وشريحة ليمون.',
                ],
            ],
        ];

        foreach ($recipes as $data) {
            Recipe::create($data);
        }
    }
}
